name: test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fluentd-version: [v1.14, v1.15, v1.16]
    services:
      fluentd:
        image: fluent/fluentd:${{ matrix.fluentd-version }}
        ports:
          - 24224:24224
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run clippy
        run: cargo clippy
      - name: Run cargo fmt
        run: cargo fmt --check
      - name: Run test
        run: cargo test
